--SQL Queries
--Q1
SELECT COUNT(*) FROM EMPLOYEE WHERE SEX = 'M';
--Q2
SELECT COUNT(*) FROM EMPLOYEE WHERE DOJ  < DATE_SUB(NOW(), INTERVAL 10 YEAR);
--Q3
SELECT CONCAT(A.FIRST_NAME, " ", A.LAST_NAME) AS MANAGER,  B.DEPT_NAME AS DEPARTMENT, DATE_FORMAT(DOJ,'%d/%m/%Y') AS Joined_date  
FROM   EMPLOYEE A, DEPARTMENT B, DEPT_MANAGER C  
WHERE  A.DEPT_ID = B.DEPT_ID AND  A.DEPT_ID = C.DEPT_ID AND A.EMP_ID = C.EMP_ID AND A.DOJ = ALL(SELECT MIN(DOJ) FROM employee);
--Q4
SELECT COUNT(*), A.DEPT_ID, B.DEPT_NAME  
FROM   EMPLOYEE A, DEPARTMENT B  
WHERE INCOME > ALL(SELECT avg(income) FROM employee) and a.DEPT_ID = b.DEPT_ID GROUP by DEPT_ID;
--Q5
SELECT CONCAT(A.FIRST_NAME, " ", A.LAST_NAME) AS NAME, B.LEAVE_DAYS  
FROM EMPLOYEE A, LEAVES B 
WHERE A.EMP_ID = B.EMP_ID AND B.LEAVE_DAYS = ALL(SELECT MAX(LEAVE_DAYS) FROM LEAVES);